<?php

namespace kofoworola\Subdomains\Controller;


use Illuminate\Routing\Controller;
use kofoworola\Subdomains\Facade\Subdomains;

class SubdomainController extends Controller
{
    public function callAction($method, $parameters)
    {
        unset($parameters[Subdomains::parameter()]);
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
}